<?php echo $this->partial("_partials/siteheader.phtml", array('js' => array('/js/admin-cms.js', '/js/tiny_mce/jquery.tinymce.js')));?>
<section class="section section-padding-large">
  <div class="container">
    <div class="row-fluid">
      
			<div class="tabset tabs_style1 clearfix">
				<div class="panel tab-content" id="panel_dashboard">
				
					<h3><i class="icon-list"></i>Add Doctor</h3>
					<form class="nice" method="post" action="" enctype="multipart/form-data">
      		<div class="row">
	      		<div class="eight columns">
	      		<strong><label>Doctor Name:</label></strong>
		      		<input class="input-text" style="width:600px;" name="doctor_name" type="text" value="" />                   
              <?php  if(isset($this->error_data['doctor_name'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please Enter Doctor Name.</small><br>
				    	<?php } ?>
				    	<br><strong><label>Clinic Name:</label></strong>
		      			<select name="clinic_name">
		      			<?php foreach($this->clinicname as $row) { ?>
		      			<option value="<?php echo $row['name']; ?>"><?php echo $row['name']; ?></option>
		      			<?php } ?>
		      			</select>                  
              <?php  if(isset($this->error_data['clinic_name'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please Enter Clinic Name.</small><br>
				    	<?php } ?>	
				    	<br><strong><label>Doctor Title:</label></strong>
		      		<input class="input-text" style="width:600px;" name="doctor_title" type="text" value="" />                   
              <?php  if(isset($this->error_data['doctor_title'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please Enter Doctor Title.</small><br>
				    	<?php } ?>
				    	<br><strong><label>Clinic Details:</label></strong>
		      		<textarea name="clinic_details" style="width:600px" rows="5"></textarea>
              <?php  if(isset($this->error_data['clinic_details'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please Enter Description</small><br>
				    	<?php } ?>
				    	<br><strong><label>Clinic Area:</label></strong>
		      		<input class="input-text" style="width:600px;" id="area" name="area" type="text" value="" readonly/>                   
              <?php  if(isset($this->error_data['area'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please pick on the map to get the area.</small><br>
				    	<?php } ?>
				    	<br><strong><label>Clinic Address:</label></strong>
		      		<input class="input-text" style="width:600px;" id="clinic_address" name="clinic_address" type="text" readonly/>
		      		<input name="lat" id="lat" type="hidden"/>
		      		<input name="lon" id="lon" type="hidden"/>
              <?php  if(isset($this->error_data['clinic_address'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please pick on the map to get the address</small><br>				    	
				    	<?php } ?>
				    	<div id="map_canvas" style="width:800px; height:400px;"></div>
				    	<br>
		      	</div>
		      	<script>
		      		var marker=null;
		      		function initialize() {
				        var map_canvas = document.getElementById('map_canvas');
				        var map_options = {
				          center: new google.maps.LatLng(34.0526594,-118.24481964),
				          zoom: 8,
				          mapTypeId: google.maps.MapTypeId.ROADMAP
				        }
				        var map = new google.maps.Map(map_canvas, map_options)
								google.maps.event.addListener(map, 'click', function(event) {
									if(marker==null) {
										marker = new google.maps.Marker({
										    position: event.latLng,
										    map: map,
										  });
									} else {
											marker.setPosition(event.latLng);
									}									
									var latlng = String(event.latLng);
									var pos=latlng.substring(1,latlng.length-1)
									var lat_lng=pos.split(',');
									$("#lat").val(lat_lng[0]);
									$("#lon").val(lat_lng[1]);
									$.ajax({		
										type: 'POST',
										url :  'http://maps.googleapis.com/maps/api/geocode/json?latlng='+pos+'&sensor=true',
										/*url : 'http://maps.googleapis.com/maps/api/geocode/json?latlng=44.4647452,7.3553838&sensor=true',*/
										success: function(response) {
											$("#clinic_address").val(response['results'][0]['formatted_address']);
											$("#area").val(response['results'][0]['address_components'][2]['long_name']);
										},
										error: function(request, error, status) {
											alert(status);
										}
									});									
								});				      				        
				      }
				      google.maps.event.addDomListener(window, 'load', initialize);	        	    				      		
		      	</script>
		    </div>
		    <div class="row">
	      		<input type="submit" class="medium radius green button" value="Add Content" />
		    </div>
		</form>  
				</div>
      <div class="gap" style="height:50px"></div>
    </div>
  </div>
</section>