<?php echo $this->partial("_partials/siteheader.phtml", array('heading'=>'areas','js' => array('/js/admin-cms.js','/js/tiny_mce/jquery.tinymce.js')));?>
<section class="section section-padding-large">
  <div class="container">
    <div class="row-fluid">
      
			<div class="tabset tabs_style1 clearfix">
				<div class="panel tab-content" id="panel_dashboard">
				
					<h3><i class="icon-list"></i>Areas</h3>
					<div style="float:right;"><?php echo $this->paginator; ?></div>	
						<form class="nice">
			<table style="width: 100%;">
				<thead>
					<tr>
						<th width="10%">S. No</th>
						<th width="20%">Name</th>
						<th width="25%">Record Date</th>
						<th width="15%">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php if(sizeof($this->paginator)>0) { ?>
					<?php $i=0; foreach ($this->paginator as $row) { $i++; ?><tr>
					<tr>
						<td style="vertical-align:top;" align="center"><?php echo $i;?></td>
						<td style="vertical-align:top;" align="center"><?php echo $row['name']; ?></td>
						<td style="vertical-align:top;" align="center"><?php echo $row['create_date'];?></td>
						<td style="vertical-align:top;" align="center"><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'edit-areas', 'id' => $row['id']), null, true);?>">Edit</a> | <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'delete-areas', 'id' => $row['id']), null, true);?>">Delete</a></td>
					</tr>
					<?php } } else {?>
						<tr><td colspan="5" align="center">There is no areas.</td></tr>
					<?php } ?>
				</tbody>
			</table>
		</form>
        <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'add-areas'), null, true);?>" class="medium radius green button">Add Areas</a>
				</div>
      <div class="gap" style="height:50px"></div>
    </div>
  </div>
</section>