<?php echo $this->partial("_partials/siteheader.phtml", array('heading'=>'doctors'));?>
<section class="section section-padding-large">
  <div class="container">
    <div class="row-fluid">
      
			<div class="tabset tabs_style1 clearfix">
				<div class="panel tab-content" id="panel_dashboard">
				
					<h3><i class="icon-list"></i>Doctors</h3>
					<div style="float:right;"><?php echo $this->paginator; ?></div>	
						<table>
							<thead>
								<tr>
									<th width="10%">S. No</th>
									<th width="20%">Doctor Name</th>
									<th width="20%">Clinic Name</th>
									<th width="20%">Doctor Title</th>
									<th width="15%">Clinic Area</th>
									<th width="15%">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php if(sizeof($this->paginator)>0) { ?>
								<?php
									$i=0;
									foreach ($this->paginator as $row) { $i++;
								?>
								<tr>
									<td style="vertical-align:top;" align="center"><?php echo $i; ?></td>
									<td style="vertical-align:top;" align="center"><?php echo $row['doctor_name']; ?></td>
									<td style="vertical-align:top;" align="center"><?php echo $row['clinic_name']; ?></td>
									<td style="vertical-align:top;" align="center"><?php echo $row['doctor_title']; ?></td>
									<td style="vertical-align:top;" align="center"><?php echo $row['area']; ?></td>
									<td style="vertical-align:top;" align="center"><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'edit-doctors', 'id' => $row['id']), null, true);?>">Edit</a>&nbsp;|&nbsp;<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'delete-doctors', 'id' => $row['id']), null, true);?>">Delete</a></td>
								</tr>
								<?php } } else {?>
									<tr><td colspan="6" align="center">There is no doctor listing.</td></tr>
								<?php } ?>
							</tbody>
						</table>
						<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'add-doctors'), null, true);?>" class="medium radius green button">Add Doctors</a>
				</div>
      <div class="gap" style="height:50px"></div>
    </div>
  </div>
</section>
