<?php echo $this->partial("_partials/siteheader.phtml", array('js' => array('/js/admin-cms.js', '/js/tiny_mce/jquery.tinymce.js')));?>
<section class="section section-padding-large">
  <div class="container">
    <div class="row-fluid">
      
			<div class="tabset tabs_style1 clearfix">
				<div class="panel tab-content" id="panel_dashboard">
				
					<h3><i class="icon-list"></i>Edit Product</h3>
					<form class="nice" method="post" action="" enctype="multipart/form-data">
      		<div class="row">
	      		<div class="eight columns">  
	      			<strong><label>Name:</label></strong>
		      		<input class="input-text" style="width:600px;" name="name" type="text" value="<?php echo $this->products_data['name']; ?>" />
              			<?php  if(isset($this->error_data['name'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please Enter Name.</small><br>
				    	<?php } ?>
				    	<br>           
		      		<strong><label>Image:</label></strong><br>
		     		<input class="input-text" type="file" name="products-image" id="products-image" value="" />
		     		<div id="uploadimage"><img id="photo" width="150px" src="<?php echo $this->baseURL().'/images/products/'.$this->products_data['image']; ?>" /></div>
             <?php if(isset($this->error_data['products-image'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please Select your Image.</small><br>
				    	<?php } ?>
		       		<br><strong><label>Description:</label></strong>
		      		<textarea name="description" style="width:600px" rows="2"><?php echo $this->products_data['description']; ?></textarea>
              <?php  if(isset($this->error_data['description'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please enter description.</small><br>
				    	<?php } ?>
				    	<Br>
				    	<strong><label>Price:</label></strong>
		      		<input class="input-text" style="width:600px;" name="price" type="text" value="<?php echo $this->products_data['price']; ?>" />                   
              			<?php  if(isset($this->error_data['price'])) { ?>                        
				    	<small class="error" style="margin-top:5px !important; width:252px !important;">Please Enter price.</small><br>
				    	<?php } ?>
		      	</div>
		      	<script>
        	    function readURL(input,val) {
				        if (input.files && input.files[0]) {
						            var reader = new FileReader();
						            
						            reader.onload = function (e) {
						                $(val).attr('src', e.target.result);
						            }
						            
						            reader.readAsDataURL(input.files[0]);
						        }
						    }						    
						    $("#products-image").change(function(){
						        readURL(this,'#photo');
						        document.getElementById("uploadimage").style.display="block";
						    });	      		
		      	</script>
		    </div>
		    <div class="row">
	      		<input type="submit" class="medium radius green button" value="Edit Product" />
		    </div>
		</form>  
				</div>
      <div class="gap" style="height:50px"></div>
    </div>
  </div>
</section>