<?php  echo $this->partial("_partials/siteheader.phtml", array('js' => '',
	'css'=>'', 'heading' => 'Home'));	
?>	          
                    
  <!-- rev  slider -->

<div id="rev_slider_3_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container">
  <div id="rev_slider_3_1" class="rev_slider fullwidthabanner" >
    <ul>
      <li data-transition="fade" data-slotamount="7" data-masterspeed="300" > <img src="images/slide-bg1.jpg"  alt="slide-bg1"  data-fullwidthcentering="on">
        <div class="tp-caption fade"
					 data-x="50" 
					 data-y="0" 					 data-speed="500" 
					 data-start="500" 
					 data-easing="easeOutExpo"  ><img src="images/man.png" alt="Image 2"> </div>
        <div class="tp-caption bg-title sfb"
					 data-x="570" 
					 data-y="150" 					 data-speed="400" 
					 data-start="800" 
					 data-easing="easeOutExpo"  >The No.1 Online</div>
        <div class="tp-caption bg-title sfb"
					 data-x="570" 
					 data-y="198" 					 data-speed="400" 
					 data-start="1100" 
					 data-easing="easeOutExpo"  > <span>English School in Japan</span> </div>
        <div class="tp-caption bg-subtitle fade"
					 data-x="575" 
					 data-y="270" 					 data-speed="300" 
					 data-start="1400" 
					 data-easing="easeOutExpo"  >Become an ONLINE-BASED ENGLISH TUTOR at RAREJOB!<br />
          Become an ONLINE-BASED ENGLISH TUTOR at RAREJOB!</div>
        <div class="tp-caption fade bg-buttons"
					 data-x="570" 
					 data-y="360" 					 data-speed="300" 
					 data-start="1700" 
					 data-easing="easeOutExpo"  ><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'index'), null, true);?>" class='button'>Apply Now!</a></div>
      </li>
      <li data-transition="fade" data-slotamount="7" data-masterspeed="300" > <img src="images/slider-bg2.png"  alt="slide-bg1-1140x600"  data-fullwidthcentering="on">
        <div class="tp-caption sfb"
					 data-x="70" 
					 data-y="50" 					 data-speed="300" 
					 data-start="500" 
					 data-easing="easeOutExpo"  ><img src="images/responsive_ipad.png" alt="Image 1"> </div>
        <div class="tp-caption sfb"
					 data-x="340" 
					 data-y="200" 					 data-speed="300" 
					 data-start="700" 
					 data-easing="easeOutExpo"  ><img src="images/responsive_mobile.png" alt="Image 1"> </div>
        <div class="tp-caption bg-title-white sfb"
					 data-x="550" 
					 data-y="155" 					 data-speed="400" 
					 data-start="900" 
					 data-easing="easeOutExpo"  >Ultra Responsive Layout </div>
        <div class="tp-caption bg-title-white sfb"
					 data-x="550" 
					 data-y="200" 					 data-speed="400" 
					 data-start="1300" 
					 data-easing="easeOutExpo"  > <span>with a clean design</span> </div>
        <div class="tp-caption bg-subtitle-white fade"
					 data-x="550" 
					 data-y="270" 					 data-speed="300" 
					 data-start="1700" 
					 data-easing="easeOutExpo">Blandes is fully responsive so your content will look <br />
          great on every
          device and every time </div>
        <div class="tp-caption bg-buttons-white fade"
					 data-x="550" 
					 data-y="355" 					 data-speed="300" 
					 data-start="2100" 
					 data-easing="easeOutExpo"><a href='#' class='button white'>Buy Now</a><a href='#' class='readmore'>Read More<i class="icon-arrow-right6"></i></a></div>
      </li>
      <li data-transition="fade" data-slotamount="7" data-masterspeed="300" > <img src="images/slide-bg1.jpg"  alt="Slide background"  data-fullwidthcentering="on">
        <div class="tp-caption sfb"
					 data-x="0" 
					 data-y="120" 					 data-speed="400" 
					 data-start="500" 
					 data-easing="easeOutExpo"  ><img src="images/ipad_hand.png" alt="Image 1"> </div>
        <div class="tp-caption sfb"
					 data-x="170" 
					 data-y="155" 					 data-speed="400" 
					 data-start="500" 
					 data-easing="easeOutExpo"  >
          <iframe src='http://player.vimeo.com/video/68433687?title=0&amp;byline=0&amp;portrait=0;api=1' width='365' height='270' style='width:365px;height:270px;'></iframe>
        </div>
        <div class="tp-caption bg-title sfb"
					 data-x="570" 
					 data-y="150" 					 data-speed="400" 
					 data-start="800" 
					 data-easing="easeOutExpo">Easy and Fun to embed </div>
        <div class="tp-caption bg-title sfb"
					 data-x="570" 
					 data-y="195" 					 data-speed="400" 
					 data-start="1100" 
					 data-easing="easeOutExpo"><span>youtube videos</span> </div>
        <div class="tp-caption bg-subtitle fade"
					 data-x="570" 
					 data-y="265" 					 data-speed="300" 
					 data-start="1400" 
					 data-easing="easeOutExpo"  >Lorem ipsum dolor sit amet, consectetur adipiscing elit <br />
          Phasellus non cursus augue, ac eleifend odio.</div>
        <div class="tp-caption bg-buttons fade"
					 data-x="570" 
					 data-y="350" 					 data-speed="300" 
					 data-start="2100" 
					 data-easing="easeOutExpo"><a href='#' class='button'>Buy Now</a><a href='#' class='readmore'>Read More<i class="icon-arrow-right6"></i></a></div>
      </li>
    </ul>
  </div>
</div>
<script type="text/javascript">

								
				var revapi3;
				
				jQuery(document).ready(function() {
				
				if (jQuery.fn.cssOriginal != undefined)
					jQuery.fn.css = jQuery.fn.cssOriginal;
				
				if(jQuery('#rev_slider_3_1').revolution == undefined)
					revslider_showDoubleJqueryError('#rev_slider_3_1');
				else {
				   revapi3 = jQuery('#rev_slider_3_1').show().revolution(
					{
						delay:9000,
						startwidth:1140,
						startheight:500,
						hideThumbs:200,
						
						thumbWidth:100,
						thumbHeight:50,
						thumbAmount:3,
						
						navigationType:"bullet",
						navigationArrows:"solo",
						navigationStyle:"round",
						
						touchenabled:"on",
						onHoverStop:"on",
						
						navigationHAlign:"center",
						navigationVAlign:"bottom",
						navigationHOffset:0,
						navigationVOffset:30,

						soloArrowLeftHalign:"left",
						soloArrowLeftValign:"center",
						soloArrowLeftHOffset:10,
						soloArrowLeftVOffset:0,

						soloArrowRightHalign:"right",
						soloArrowRightValign:"center",
						soloArrowRightHOffset:10,
						soloArrowRightVOffset:0,
								
						shadow:0,
						fullWidth:"on",
						fullScreen:"off",

						stopLoop:"off",
						stopAfterLoops:-1,
						stopAtSlide:-1,

						shuffle:"off",
						
						hideSliderAtLimit:0,
						hideCaptionAtLimit:0,
						hideAllCaptionAtLilmit:0,
						startWithSlide:0,
						videoJsPath:"revslider/videojs/",
						fullScreenOffsetContainer: ""	
					});
					
					revapi3.revnext(function(){alert(0)});
				}
				});	//ready
				
				
			</script> 

<!-- END REVOLUTION SLIDER --> 

<!-- Section post -->

<section class="section section-blue ftw">
  <div class="container">
    <div class="row-fluid">
      <div class="row-fluid ">
        <div class="span4">
          <div class="inner-content vertical-padding-large">
            <div class="feature_box  style2"> <span class="fontAwesomeIcon style1 "><i class="icon-blandes-study ftw"></i></span>
              <h3 class="ftw">Teach Online at Home</h3>
              <p>Teach English to Japanese students online in the comfort of your own home.<br>
Even the entire application process is done online!</p>
              <a class="readmore ftw" href="#">Read More<i class="icon-arrow-right8"></i></a> </div>
          </div>
        </div>
        <div class="span4">
          <div class="inner-content  vertical-padding-large">
            <div class="feature_box  style2"> <span class="fontAwesomeIcon style1  "><i class="icon-blandes-calendar ftw"></i></span>
              <h3 class="ftw">Manage your Own Schedule</h3>
              <p>Manage your own schedule and choose when to teach. Cancel lessons up to at least 2 days in advance. Great for college students and working professionals. </p>
              <a class="readmore ftw" href="#">Read More<i class="icon-arrow-right8"></i></a> </div>
          </div>
        </div>
        <div class="span4">
          <div class="inner-content  vertical-padding-large">
            <div class="feature_box  style2"> <span class="fontAwesomeIcon style1  "><i class="icon-blandes-banknote ftw"></i></span>
              <h3 class="ftw">Earn Big Money</h3>
              <p>Earn as much as PhP 25,000 per month depending on the number of hours you teach. </p>
              <a class="readmore ftw" href="#">Read More<i class="icon-arrow-right8"></i></a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section section-padding-large section-border-yes section-grey"  >
  <div class="container">
    <div class="row-fluid ">
      <h2 class="textcenter textuppercase title"> <span>About us</span> </h2>
      <div class="hr aligncenter double-border  border-tiny"></div>
      <div class="row-fluid style2 testimonial-grid bottom-margin-no">
        <div class="span6 testimonial-grid-item">
          <div class="inner-content  vertical-padding-large ">
            <div class="testimonial"> <img class="author-avatar" src="images/team.jpg" alt="Sam Mandis" >
              <blockquote><h4>About this site</h4>RareJob is the No.1 Online English school in Japan in terms of its number of students and tutors. We now have over 2000 home-based tutors who teach in RareJob and earn money every month. </blockquote>
            </div>
          </div>
        </div>
        <div class="span6 testimonial-grid-item">
          <div class="inner-content  vertical-padding-large ">
            <div class="testimonial"> <img class="author-avatar" src="images/testimonial.jpg" alt="Sara Mandis" >
              <blockquote><h4>About online English lesson</h4>When I came to the Philippines, I was shocked because there are so many excellent people who are not well-compensated due to geographical reasons. RareJob tries to give opportunities beyond borders.<br>

RareJob does not only provide opportunities for Japanese to learn English - it also provides opportunities for excellent Filipinos to work and earn at home.<br>

Why not become a tutor in RareJob now? </blockquote>
              <div class="author-info"> <span class="name"> Tomohisa Kato</span> <span class="divider">/</span> <span class="company"> RareJob CEO </span> </div>
            </div>
          </div>
        </div>
      </div>
      <div class="gap"></div>
    </div>
  </div>
</section>
<section class="section full-width-carousel"> <!--<a class="carousel-prev" href="#"></a> <a class="carousel-next" href="#"></a>-->
  <div class="container">
    <div class="row-fluid">
      <div class="row-fluid">
        <div class="span6 carousel-slides" >
          <div class="inner-content">
            <div class="carousel-slides-container carousel-ipad-slideshow-container">
              <div class="carousel-ipad-slideshow">
                <div class="image"><img src="images/ipad-frame.png" alt=""></div>
              </div>
              <div class="carousel-images"> <img src="images/ipad-slideshow.jpg" data-caption="carousel_content1" alt=""> <img src="images/ipad-slideshow.jpg" data-caption="carousel_content2" alt=""> <img src="images/ipad-slideshow.jpg" data-caption="carousel_content3" alt=""> </div>
            </div>
          </div>
        </div>
        <div class="span6" >
          <div class="inner-content">
            <div class="carousel-content-container">
              <div class="carousel-content" id="carousel_content1">
                <h2 class="textuppercase"> Sample Lesson</h2>
                <div class="hr border-tiny double-border"></div>
                <p>Phasellus enim libero, blandit vel sapi condimentum ultricies magna Quisque euismod orci ut et lobortis aliquam aliquam in tortor et lobortis aliquam Phasellus enim libero, blandit vel sapi condimentum ultricies magnis</p>
                <ul class="styled-list style3">
                  <li><i class="icon-arrow-right4"></i>Install demo content easily  with just one click that come with original template</li>
                  <li><i class="icon-arrow-right4"></i>Crafted with cutting edge and w3c valid HTML5, CSS3 and javascript code</li>
                  <li><i class="icon-arrow-right4"></i>Fully Reponsive layout so your content always look great on any device</li>
                  <li><i class="icon-arrow-right4"></i>Incridbly Robust sliders to showcase your content and images</li>
                  <li><i class="icon-arrow-right4"></i>Fully out of solution so you do't need to write any hardcore code</li>
                </ul>
                <div class="hr border-tiny double-border"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<?php echo $this->partial("_partials/sitefooter.phtml");?>